import type { Property } from './types';

export const properties: Property[] = [
  {
    id: 'stay-mumbai-1',
    title: 'Modern Loft with Sea View',
    type: 'Stay',
    category: 'Apartment',
    location: 'Bandra, Mumbai',
    city: 'Mumbai',
    price: 150,
    rating: 4.9,
    reviews: 250,
    images: ['https://picsum.photos/seed/stay-mumbai-1-1/800/600', 'https://picsum.photos/seed/stay-mumbai-1-2/800/600', 'https://picsum.photos/seed/stay-mumbai-1-3/800/600'],
    details: 'A stunning loft apartment in the heart of Bandra with breathtaking views of the Arabian Sea. This spacious and stylish home features modern decor, a fully equipped kitchen, and a cozy balcony. Perfect for couples or solo travelers looking for a chic city escape.',
    summary: 'Experience chic urban living in this stylish Bandra loft, offering spectacular sea views and modern comforts for a memorable Mumbai getaway.',
    amenities: ['Wifi', 'Air Conditioning', 'Kitchen', 'TV', 'Sea View'],
    host: { name: 'Aisha Sharma', avatar: 'https://picsum.photos/seed/host-aisha/100/100', joinYear: 2018 },
  },
  {
    id: 'stay-delhi-1',
    title: 'Heritage Haveli in Old Delhi',
    type: 'Stay',
    category: 'Boutique Hotel',
    location: 'Chandni Chowk, Delhi',
    city: 'Delhi',
    price: 120,
    rating: 4.8,
    reviews: 180,
    images: ['https://picsum.photos/seed/stay-delhi-1-1/800/600', 'https://picsum.photos/seed/stay-delhi-1-2/800/600'],
    details: 'Step back in time in this beautifully restored haveli. Located near the bustling streets of Chandni Chowk, it offers a peaceful oasis with traditional Indian architecture, a courtyard garden, and antique furnishings. Each room is uniquely decorated.',
    summary: 'Discover Old Delhi\'s charm in a restored heritage haveli, a peaceful oasis blending traditional architecture with modern comfort near Chandni Chowk.',
    amenities: ['Wifi', 'Garden', 'Room Service', 'Air Conditioning'],
    host: { name: 'Rohan Mehra', avatar: 'https://picsum.photos/seed/host-rohan/100/100', joinYear: 2016 },
  },
  {
    id: 'stay-goa-1',
    title: 'Beachfront Villa with Private Pool',
    type: 'Stay',
    category: 'Villa',
    location: 'Anjuna, Goa',
    city: 'Goa',
    price: 300,
    rating: 4.95,
    reviews: 320,
    images: ['https://picsum.photos/seed/stay-goa-1-1/800/600', 'https://picsum.photos/seed/stay-goa-1-2/800/600', 'https://picsum.photos/seed/stay-goa-1-3/800/600', 'https://picsum.photos/seed/stay-goa-1-4/800/600'],
    details: 'An exclusive beachfront villa in North Goa offering luxury and privacy. Features a private infinity pool, direct beach access, a sun deck, and three spacious bedrooms. Ideal for families or groups seeking a lavish coastal retreat.',
    summary: 'Indulge in luxury at this exclusive Anjuna beachfront villa, complete with a private pool and direct beach access for the ultimate Goan retreat.',
    amenities: ['Private Pool', 'Beach Access', 'Wifi', 'Full Kitchen', 'Air Conditioning'],
    host: { name: 'Priya Fernandes', avatar: 'https://picsum.photos/seed/host-priya/100/100', joinYear: 2019 },
  },
  {
    id: 'experience-mumbai-1',
    title: 'Mumbai Street Food Tour',
    type: 'Experience',
    category: 'Food Tour',
    location: 'Multiple, Mumbai',
    city: 'Mumbai',
    price: 40,
    rating: 4.9,
    reviews: 500,
    images: ['https://picsum.photos/seed/exp-mumbai-1-1/800/600', 'https://picsum.photos/seed/exp-mumbai-1-2/800/600'],
    details: 'Embark on a culinary adventure through the streets of Mumbai. Taste iconic dishes like Vada Pav, Pav Bhaji, and Pani Puri from the city\'s most famous and hygienic vendors. A local guide will share stories behind the food and the city.',
    summary: 'Taste the heart of Mumbai on a guided street food tour. Savor iconic local dishes while uncovering the vibrant stories behind the city\'s culinary culture.',
    amenities: ['Local Guide', 'Food Tastings', 'Water Bottle'],
    host: { name: 'Sanjay Kapoor', avatar: 'https://picsum.photos/seed/host-sanjay/100/100', joinYear: 2017 },
  },
  {
    id: 'stay-bengaluru-1',
    title: 'Tech Hub Garden Apartment',
    type: 'Stay',
    category: 'Apartment',
    location: 'Koramangala, Bengaluru',
    city: 'Bengaluru',
    price: 90,
    rating: 4.7,
    reviews: 150,
    images: ['https://picsum.photos/seed/stay-bengaluru-1-1/800/600', 'https://picsum.photos/seed/stay-bengaluru-1-2/800/600'],
    details: 'A tranquil 1-bedroom apartment with a lush private garden, located in the vibrant neighborhood of Koramangala. Close to tech parks and top restaurants, it features a dedicated workspace with high-speed internet, making it perfect for business travelers.',
    summary: 'Find peace in the heart of Bengaluru\'s tech hub. This Koramangala apartment offers a private garden and dedicated workspace for a perfect work-life balance.',
    amenities: ['Wifi', 'Workspace', 'Garden', 'Kitchen', 'Air Conditioning'],
    host: { name: 'Anjali Rao', avatar: 'https://picsum.photos/seed/host-anjali/100/100', joinYear: 2020 },
  },
  {
    id: 'service-goa-1',
    title: 'Airport Transfer - Goa',
    type: 'Service',
    category: 'Transportation',
    location: 'Goa International Airport',
    city: 'Goa',
    price: 25,
    rating: 4.9,
    reviews: 800,
    images: ['https://picsum.photos/seed/service-goa-1-1/800/600'],
    details: 'Reliable and comfortable private airport transfer from Goa International Airport (GOI) to any hotel in North or South Goa. Professional driver, air-conditioned vehicle, and hassle-free service. Available 24/7.',
    summary: 'Enjoy a seamless start to your Goa trip with a reliable, 24/7 private airport transfer in a comfortable, air-conditioned vehicle.',
    amenities: ['Private Car', 'Professional Driver', '24/7 Service'],
    host: { name: 'GoaTransfers', avatar: 'https://picsum.photos/seed/host-goa-transfers/100/100', joinYear: 2015 },
  },
  {
    id: 'experience-delhi-1',
    title: 'Sunrise at the Taj Mahal Tour from Delhi',
    type: 'Experience',
    category: 'Day Trip',
    location: 'Agra (from Delhi)',
    city: 'Delhi',
    price: 150,
    rating: 4.95,
    reviews: 1200,
    images: ['https://picsum.photos/seed/exp-delhi-1-1/800/600', 'https://picsum.photos/seed/exp-delhi-1-2/800/600'],
    details: 'A private day trip from Delhi to witness the breathtaking beauty of the Taj Mahal at sunrise. The tour includes a private air-conditioned car, a professional guide in Agra, and visits to Agra Fort. A truly unforgettable experience.',
    summary: 'Witness the majestic Taj Mahal at sunrise on a private day trip from Delhi. This all-inclusive tour with a personal guide promises an unforgettable experience.',
    amenities: ['Private Car', 'Guide', 'Monuments Entry (optional)'],
    host: { name: 'India Tours', avatar: 'https://picsum.photos/seed/host-india-tours/100/100', joinYear: 2012 },
  },
  {
    id: 'stay-mumbai-2',
    title: 'Cozy Studio in Juhu',
    type: 'Stay',
    category: 'Studio',
    location: 'Juhu, Mumbai',
    city: 'Mumbai',
    price: 80,
    rating: 4.6,
    reviews: 110,
    images: ['https://picsum.photos/seed/stay-mumbai-2-1/800/600'],
    details: 'A compact and cozy studio apartment just a short walk from Juhu Beach. Well-suited for solo adventurers or couples. It has a small kitchenette and all the essential amenities for a comfortable stay in a prime Mumbai location.',
    summary: 'Discover Mumbai from this cozy Juhu studio, just steps from the beach. It\'s the perfect, compact base for solo travelers or couples.',
    amenities: ['Wifi', 'Kitchenette', 'Air Conditioning', 'TV'],
    host: { name: 'Vikram Singh', avatar: 'https://picsum.photos/seed/host-vikram/100/100', joinYear: 2021 },
  },
  {
    id: 'stay-goa-2',
    title: 'Riverside Cabin in South Goa',
    type: 'Stay',
    category: 'Cabin',
    location: 'Palolem, Goa',
    city: 'Goa',
    price: 70,
    rating: 4.8,
    reviews: 210,
    images: ['https://picsum.photos/seed/stay-goa-2-1/800/600', 'https://picsum.photos/seed/stay-goa-2-2/800/600'],
    details: 'Escape to this serene riverside cabin in the tranquil south of Goa. Surrounded by lush greenery, it offers a peaceful retreat away from the crowds. Enjoy the simple life with a comfortable bed, a private balcony, and the sounds of nature.',
    summary: 'Find serenity in a lush, riverside cabin in South Goa. This peaceful retreat offers a simple, comfortable escape surrounded by nature\'s soundtrack.',
    amenities: ['Balcony', 'River View', 'Fan'],
    host: { name: 'Maria D\'Souza', avatar: 'https://picsum.photos/seed/host-maria/100/100', joinYear: 2018 },
  },
  {
    id: 'experience-bengaluru-1',
    title: 'Traditional South Indian Cooking Class',
    type: 'Experience',
    category: 'Cooking Class',
    location: 'Indiranagar, Bengaluru',
    city: 'Bengaluru',
    price: 50,
    rating: 4.9,
    reviews: 150,
    images: ['https://picsum.photos/seed/exp-bengaluru-1-1/800/600', 'https://picsum.photos/seed/exp-bengaluru-1-2/800/600'],
    details: 'Learn the secrets of authentic South Indian cuisine in a local home. This hands-on cooking class will teach you how to prepare classic dishes like Dosa, Idli, and Sambar from scratch. Enjoy the delicious meal you helped create.',
    summary: 'Master the art of South Indian cuisine in a hands-on cooking class. Learn to make classics like Dosa and Sambar in a local home.',
    amenities: ['Hands-on Class', 'Lunch/Dinner', 'Recipes'],
    host: { name: 'Mrs. Padma', avatar: 'https://picsum.photos/seed/host-padma/100/100', joinYear: 2019 },
  },
  {
    id: 'service-delhi-1',
    title: 'Private Chef for a Night',
    type: 'Service',
    category: 'Culinary',
    location: 'Your Location, Delhi',
    city: 'Delhi',
    price: 200,
    rating: 5.0,
    reviews: 90,
    images: ['https://picsum.photos/seed/service-delhi-1-1/800/600'],
    details: 'Hire a professional chef to cook a gourmet Indian meal in the comfort of your home or rental. The experience includes menu consultation, grocery shopping, cooking, and cleaning up. Perfect for a special occasion.',
    summary: 'Elevate your evening with a private chef who will craft a gourmet Indian meal in your Delhi home, handling everything from shopping to cleanup.',
    amenities: ['Custom Menu', 'All Ingredients', 'Full Service'],
    host: { name: 'Chef Karan', avatar: 'https://picsum.photos/seed/host-karan/100/100', joinYear: 2020 },
  },
  {
    id: 'stay-delhi-2',
    title: 'Artistic Studio in Hauz Khas Village',
    type: 'Stay',
    category: 'Studio',
    location: 'Hauz Khas Village, Delhi',
    city: 'Delhi',
    price: 95,
    rating: 4.7,
    reviews: 130,
    images: ['https://picsum.photos/seed/stay-delhi-2-1/800/600', 'https://picsum.photos/seed/stay-delhi-2-2/800/600'],
    details: 'A vibrant and artistic studio located in the trendy Hauz Khas Village, overlooking the lake. The space is filled with unique art, has a private balcony, and is surrounded by boutiques, cafes, and historical ruins. A creative\'s paradise.',
    summary: 'Immerse yourself in creativity at this artistic Hauz Khas studio. Enjoy lake views, a private balcony, and vibrant surroundings in Delhi\'s trendiest neighborhood.',
    amenities: ['Wifi', 'Lake View', 'Balcony', 'Kitchenette'],
    host: { name: 'Anika Patel', avatar: 'https://picsum.photos/seed/host-anika/100/100', joinYear: 2019 },
  },
  {
    id: 'experience-goa-1',
    title: 'Kayaking in Goa\'s Backwaters',
    type: 'Experience',
    category: 'Adventure',
    location: 'Sal Backwaters, Goa',
    city: 'Goa',
    price: 30,
    rating: 4.8,
    reviews: 250,
    images: ['https://picsum.photos/seed/exp-goa-1-1/800/600', 'https://picsum.photos/seed/exp-goa-1-2/800/600'],
    details: 'Paddle through the serene and beautiful backwaters of the Sal River. This guided kayaking tour takes you through mangrove forests where you can spot a variety of birds and other wildlife. Suitable for all skill levels, including beginners.',
    summary: 'Explore Goa\'s tranquil side with a guided kayaking tour on the Sal River. Paddle through lush mangrove forests and spot diverse wildlife.',
    amenities: ['Kayak & Gear', 'Guide', 'Refreshments'],
    host: { name: 'Goan Adventures', avatar: 'https://picsum.photos/seed/host-goan-adv/100/100', joinYear: 2016 },
  },
  {
    id: 'stay-bengaluru-2',
    title: 'Luxury Skyscraper Apartment',
    type: 'Stay',
    category: 'Apartment',
    location: 'Rajajinagar, Bengaluru',
    city: 'Bengaluru',
    price: 220,
    rating: 4.9,
    reviews: 190,
    images: ['https://picsum.photos/seed/stay-bengaluru-2-1/800/600', 'https://picsum.photos/seed/stay-bengaluru-2-2/800/600', 'https://picsum.photos/seed/stay-bengaluru-2-3/800/600'],
    details: 'Live in the sky in this luxurious 2-bedroom apartment on the 30th floor. Offers panoramic views of the city skyline, access to a rooftop pool, a state-of-the-art gym, and a private cinema. The height of urban luxury.',
    summary: 'Experience ultimate urban luxury from a 30th-floor apartment in Bengaluru, featuring stunning city views, a rooftop pool, and premium amenities.',
    amenities: ['Rooftop Pool', 'Gym', 'City View', 'Wifi', 'Full Kitchen'],
    host: { name: 'Prestige Stays', avatar: 'https://picsum.photos/seed/host-prestige/100/100', joinYear: 2018 },
  },
  {
    id: 'experience-mumbai-2',
    title: 'Bollywood Dance Class',
    type: 'Experience',
    category: 'Workshop',
    location: 'Andheri, Mumbai',
    city: 'Mumbai',
    price: 35,
    rating: 4.8,
    reviews: 300,
    images: ['https://picsum.photos/seed/exp-mumbai-2-1/800/600'],
    details: 'Learn energetic Bollywood dance moves from a professional choreographer in the heart of the film industry. This 2-hour class is fun, high-energy, and suitable for all ages and dance levels. You\'ll learn a full routine to a popular song.',
    summary: 'Unleash your inner star in a fun, high-energy Bollywood dance class in Mumbai. Learn a full routine from a pro choreographer.',
    amenities: ['Dance Instructor', 'Studio Access'],
    host: { name: 'BollyMoves', avatar: 'https://picsum.photos/seed/host-bollymoves/100/100', joinYear: 2019 },
  },
  {
    id: 'service-mumbai-1',
    title: 'Personal Stylist & Shopping Tour',
    type: 'Service',
    category: 'Fashion',
    location: 'Various Malls & Boutiques, Mumbai',
    city: 'Mumbai',
    price: 250,
    rating: 4.9,
    reviews: 70,
    images: ['https://picsum.photos/seed/service-mumbai-1-1/800/600'],
    details: 'Get a fashion makeover with a personal stylist in Mumbai. This service includes a style consultation and a guided shopping tour of both high-end boutiques and hidden local gems, tailored to your budget and taste.',
    summary: 'Revamp your style with a personal stylist in Mumbai. Enjoy a tailored consultation and a guided shopping tour of the city\'s best fashion spots.',
    amenities: ['Personal Stylist', 'Style Consultation', 'Guided Shopping'],
    host: { name: 'StyleMe Mumbai', avatar: 'https://picsum.photos/seed/host-styleme/100/100', joinYear: 2021 },
  },
  {
    id: 'stay-jaipur-1',
    title: 'Royal Palace Suite',
    type: 'Stay',
    category: 'Heritage Hotel',
    location: 'Amer, Jaipur',
    city: 'Jaipur',
    price: 400,
    rating: 4.98,
    reviews: 450,
    images: ['https://picsum.photos/seed/stay-jaipur-1-1/800/600', 'https://picsum.photos/seed/stay-jaipur-1-2/800/600', 'https://picsum.photos/seed/stay-jaipur-1-3/800/600'],
    details: 'Live like royalty in a suite within a restored wing of a historic palace near Amer Fort. This opulent room features traditional Rajasthani decor, a four-poster bed, and stunning views of the Aravalli hills. Includes access to palace gardens and fine dining.',
    summary: 'Experience royal life in a historic palace suite near Amer Fort. This opulent room offers Rajasthani decor and breathtaking hill views.',
    amenities: ['Room Service', 'Fine Dining', 'Pool', 'Historic Property'],
    host: { name: 'The Royal Heritage', avatar: 'https://picsum.photos/seed/host-royal/100/100', joinYear: 2010 },
  },
  {
    id: 'experience-jaipur-1',
    title: 'Block Printing Workshop',
    type: 'Experience',
    category: 'Craft',
    location: 'Bagru, Jaipur',
    city: 'Jaipur',
    price: 45,
    rating: 4.9,
    reviews: 280,
    images: ['https://picsum.photos/seed/exp-jaipur-1-1/800/600', 'https://picsum.photos/seed/exp-jaipur-1-2/800/600'],
    details: 'Visit the artisan village of Bagru and learn the ancient art of Rajasthani block printing from a master craftsman. You will get to design and print your own scarf or tote bag to take home as a unique souvenir.',
    summary: 'Learn the ancient art of Rajasthani block printing in the artisan village of Bagru. Design and create your own unique printed souvenir.',
    amenities: ['Workshop Materials', 'Expert Guidance', 'Take-home Souvenir'],
    host: { name: 'Crafts of Jaipur', avatar: 'https://picsum.photos/seed/host-crafts/100/100', joinYear: 2017 },
  },
  {
    id: 'stay-kerala-1',
    title: 'Traditional Houseboat on Backwaters',
    type: 'Stay',
    category: 'Houseboat',
    location: 'Alleppey, Kerala',
    city: 'Kerala',
    price: 180,
    rating: 4.85,
    reviews: 600,
    images: ['https://picsum.photos/seed/stay-kerala-1-1/800/600', 'https://picsum.photos/seed/stay-kerala-1-2/800/600'],
    details: 'A private one-bedroom \'Kettuvallam\' (houseboat) that cruises the serene backwaters of Alleppey. The boat comes with a personal chef and a driver. Enjoy freshly cooked Keralan cuisine as you float past lush paddy fields and tranquil villages.',
    summary: 'Cruise Alleppey\'s serene backwaters on a private houseboat. Enjoy authentic Keralan meals prepared by your personal chef while floating past scenic villages.',
    amenities: ['Private Chef', 'All Meals Included', 'Full Staff'],
    host: { name: 'Kerala Dreams', avatar: 'https://picsum.photos/seed/host-kerala/100/100', joinYear: 2014 },
  },
  {
    id: 'experience-kerala-1',
    title: 'Kathakali Performance & Dinner',
    type: 'Experience',
    category: 'Culture',
    location: 'Kochi, Kerala',
    city: 'Kerala',
    price: 35,
    rating: 4.8,
    reviews: 190,
    images: ['https://picsum.photos/seed/exp-kerala-1-1/800/600'],
    details: 'Witness a captivating Kathakali performance, a traditional dance-drama of Kerala. The experience includes watching the intricate makeup process before the show, followed by a traditional Sadhya dinner served on a banana leaf.',
    summary: 'Experience the magic of Kerala with a traditional Kathakali performance. Witness the elaborate makeup process and enjoy an authentic Sadhya dinner.',
    amenities: ['Show Tickets', 'Dinner', 'Cultural Briefing'],
    host: { name: 'Kochi Arts Center', avatar: 'https://picsum.photos/seed/host-kochi-arts/100/100', joinYear: 2015 },
  },
];
