
import type { Property } from './types';

export const properties: Property[] = [
  {
    id: '1',
    title: 'Sea-facing Apartment in Bandra',
    type: 'Entire apartment',
    location: 'Mumbai, India',
    coords: { lat: 19.0760, lng: 72.8777 },
    price: 8000,
    rating: 4.9,
    reviews: 150,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'TV', 'Sea view'],
    host: {
      name: 'Rohan',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: true,
    },
    images: [
      'https://picsum.photos/seed/1/800/600',
      'https://picsum.photos/seed/2/800/600',
      'https://picsum.photos/seed/3/800/600',
      'https://picsum.photos/seed/4/800/600',
      'https://picsum.photos/seed/5/800/600',
      'https://picsum.photos/seed/6/800/600',
    ],
    details: 'Enjoy stunning sunsets from this beautiful apartment in the heart of Bandra. Located on Carter Road, you are just steps away from trendy cafes, boutiques, and the ocean. The apartment is modern, spacious, and offers breathtaking views of the Arabian Sea.',
    summary: 'A modern, spacious apartment in Mumbai\'s trendy Bandra neighborhood with stunning sea views, close to cafes and boutiques.',
    reviewDetails: [
        { id: 'r1', author: 'Priya', authorAvatar: 'https://picsum.photos/100/100', date: 'August 2024', text: 'Rohan\'s place is absolutely stunning. The view is to die for, and the apartment is clean, modern, and has everything you need. Highly recommend!' },
        { id: 'r2', author: 'Amit', authorAvatar: 'https://picsum.photos/100/100', date: 'July 2024', text: 'Amazing location in Bandra. We loved being so close to the sea and all the great restaurants. The apartment was perfect for our family.' },
        { id: 'r3', author: 'Sunita', authorAvatar: 'https://picsum.photos/100/100', date: 'July 2024', text: 'A true gem in Mumbai. The host was very responsive and helpful. Waking up to the sea view was the best part of our trip.' },
        { id: 'r4', author: 'Vikram', authorAvatar: 'https://picsum.photos/100/100', date: 'June 2024', text: 'This is a fantastic place. Very well maintained and in a prime location. Would definitely stay here again.' },
        { id: 'r5', author: 'Neha', authorAvatar: 'https://picsum.photos/100/100', date: 'May 2024', text: 'We had a wonderful time. The apartment is even better than the pictures. It\'s spacious, clean, and the views are incredible.'},
        { id: 'r6', author: 'Karan', authorAvatar: 'https://picsum.photos/100/100', date: 'May 2024', text: 'Perfect stay. Rohan is a superhost for a reason. Everything was smooth from check-in to check-out. The apartment is top-notch.' },
    ]
  },
  {
    id: '2',
    title: 'Heritage Haveli in Old Delhi',
    type: 'Private room in house',
    location: 'Delhi, India',
    coords: { lat: 28.7041, lng: 77.1025 },
    price: 4500,
    rating: 4.85,
    reviews: 280,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Air conditioning', 'Breakfast included', 'Courtyard'],
    host: {
      name: 'Aisha',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: true,
    },
    images: [
        'https://picsum.photos/seed/7/800/600',
        'https://picsum.photos/seed/8/800/600',
        'https://picsum.photos/seed/9/800/600',
        'https://picsum.photos/seed/10/800/600',
        'https://picsum.photos/seed/11/800/600',
        'https://picsum.photos/seed/12/800/600',
    ],
    details: 'Experience the charm of Old Delhi in this beautifully restored Haveli. Your room opens to a tranquil courtyard, offering a peaceful escape from the bustling city. Located near Chandni Chowk, you can easily explore historic monuments, and savor delicious street food.',
    summary: 'A restored heritage haveli in Old Delhi near Chandni Chowk, offering a tranquil courtyard and easy access to historic sites and street food.'
  },
  {
    id: '3',
    title: 'Modern Tech Hub Penthouse',
    type: 'Entire penthouse',
    location: 'Bengaluru, India',
    coords: { lat: 12.9716, lng: 77.5946 },
    price: 12000,
    rating: 4.95,
    reviews: 120,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    amenities: ['Wifi', 'Kitchen', 'Pool', 'Gym', 'Rooftop terrace'],
    host: {
      name: 'Vikram',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: true,
    },
    images: [
        'https://picsum.photos/seed/13/800/600',
        'https://picsum.photos/seed/14/800/600',
        'https://picsum.photos/seed/15/800/600',
        'https://picsum.photos/seed/16/800/600',
        'https://picsum.photos/seed/17/800/600',
        'https://picsum.photos/seed/18/800/600',
    ],
    details: 'Live in style in this luxurious penthouse in the heart of Bengaluru\'s tech corridor. The apartment offers panoramic city views from its private rooftop terrace. Featuring modern design, a gourmet kitchen, and access to a building pool and gym. Perfect for business travelers or families.',
    summary: 'Luxurious penthouse in Bengaluru\'s tech hub with a private rooftop terrace, city views, modern design, gourmet kitchen, pool, and gym access.'
  },
  {
    id: '4',
    title: 'Traditional Tamil Nadu Home',
    type: 'Entire house',
    location: 'Chennai, India',
    coords: { lat: 13.0827, lng: 80.2707 },
    price: 6000,
    rating: 4.88,
    reviews: 210,
    guests: 5,
    bedrooms: 3,
    beds: 3,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Garden'],
    host: {
      name: 'Priya',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: false,
    },
    images: [
        'https://picsum.photos/seed/19/800/600',
        'https://picsum.photos/seed/20/800/600',
        'https://picsum.photos/seed/21/800/600',
        'https://picsum.photos/seed/22/800/600',
        'https://picsum.photos/seed/23/800/600',
        'https://picsum.photos/seed/24/800/600',
    ],
    details: 'Experience authentic South Indian living in this beautifully maintained traditional home. The house features a central courtyard, antique furniture, and a lush private garden. Located in a quiet, residential neighborhood, it offers a peaceful retreat while being close to the city\'s main attractions.',
    summary: 'Authentic South Indian traditional home with a central courtyard, antique furniture, and a private garden in a quiet Chennai neighborhood.'
  },
  {
    id: '5',
    title: 'Portuguese Villa with Pool in Goa',
    type: 'Entire villa',
    location: 'Goa, India',
    coords: { lat: 15.2993, lng: 74.1240 },
    price: 15000,
    rating: 4.98,
    reviews: 180,
    guests: 8,
    bedrooms: 4,
    beds: 4,
    baths: 4,
    amenities: ['Wifi', 'Kitchen', 'Pool', 'Air conditioning', 'Beach access'],
    host: {
      name: 'Maria',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: true,
    },
    images: [
        'https://picsum.photos/seed/25/800/600',
        'https://picsum.photos/seed/26/800/600',
        'https://picsum.photos/seed/27/800/600',
        'https://picsum.photos/seed/28/800/600',
        'https://picsum.photos/seed/29/800/600',
        'https://picsum.photos/seed/30/800/600',
    ],
    details: 'Indulge in luxury at this stunning Portuguese-style villa in South Goa. With a private pool, lush gardens, and just a short walk to the beach, this is your personal paradise. The villa is spacious, with large verandas and modern amenities, perfect for a family or group holiday.',
    summary: 'A luxurious Portuguese-style villa in South Goa with a private pool, lush gardens, and easy beach access, ideal for a family or group.'
  },
  {
    id: '6',
    title: 'Royal Haveli Suite in Jaipur',
    type: 'Private room in hotel',
    location: 'Jaipur, India',
    coords: { lat: 26.9124, lng: 75.7873 },
    price: 9000,
    rating: 4.92,
    reviews: 320,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Pool', 'Air conditioning', 'Breakfast included', 'Restaurant'],
    host: {
      name: 'Maharaja',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: true,
    },
    images: [
        'https://picsum.photos/seed/31/800/600',
        'https://picsum.photos/seed/32/800/600',
        'https://picsum.photos/seed/33/800/600',
        'https://picsum.photos/seed/34/800/600',
        'https://picsum.photos/seed/35/800/600',
        'https://picsum.photos/seed/36/800/600',
    ],
    details: 'Live like royalty in this exquisite suite in a heritage haveli hotel. The suite is adorned with traditional Rajasthani art and antiques. Enjoy access to the hotel\'s beautiful pool and dine at the rooftop restaurant with views of the city. Located centrally, it is easy to explore the Pink City\'s forts and palaces.',
    summary: 'A royal suite in a Jaipur heritage hotel with Rajasthani decor, a pool, and a rooftop restaurant, centrally located for exploring the city.'
  },
  {
    id: '7',
    title: 'Colonial-Era Apartment in Kolkata',
    type: 'Entire apartment',
    location: 'Kolkata, India',
    coords: { lat: 22.5726, lng: 88.3639 },
    price: 5000,
    rating: 4.8,
    reviews: 190,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'TV'],
    host: {
      name: 'Anika',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: false,
    },
    images: [
        'https://picsum.photos/seed/37/800/600',
        'https://picsum.photos/seed/38/800/600',
        'https://picsum.photos/seed/39/800/600',
        'https://picsum.photos/seed/40/800/600',
        'https://picsum.photos/seed/41/800/600',
        'https://picsum.photos/seed/42/800/600',
    ],
    details: 'Step back in time in this charming apartment in a colonial-era building in South Kolkata. The apartment features high ceilings, vintage furniture, and a lovely balcony overlooking a leafy street. Experience the "City of Joy" from this comfortable and characterful base.',
    summary: 'A charming, colonial-era apartment in South Kolkata with high ceilings, vintage furniture, and a balcony, offering a comfortable base to explore the city.'
  },
  {
    id: '8',
    title: 'Nizam\'s Palace View Penthouse',
    type: 'Entire penthouse',
    location: 'Hyderabad, India',
    coords: { lat: 17.3850, lng: 78.4867 },
    price: 11000,
    rating: 4.94,
    reviews: 110,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    amenities: ['Wifi', 'Kitchen', 'Pool', 'Air conditioning', 'TV', 'City view'],
    host: {
      name: 'Nawab',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: true,
    },
    images: [
        'https://picsum.photos/seed/43/800/600',
        'https://picsum.photos/seed/44/800/600',
        'https://picsum.photos/seed/45/800/600',
        'https://picsum.photos/seed/46/800/600',
        'https://picsum.photos/seed/47/800/600',
        'https://picsum.photos/seed/48/800/600',
    ],
    details: 'Live the high life in this luxurious Hyderabad penthouse with views of the Chowmahalla Palace. The expansive terrace is perfect for evening gatherings. The apartment features opulent design, a modern kitchen, and access to a building pool and gym. Located in the old city, close to Charminar.',
    summary: 'Luxurious Hyderabad penthouse with palace views, an expansive terrace, opulent design, modern kitchen, and access to a pool and gym, located in the old city near Charminar.'
  },
  {
    id: '9',
    title: 'Chic Studio in Koregaon Park',
    type: 'Entire studio',
    location: 'Pune, India',
    coords: { lat: 18.5204, lng: 73.8567 },
    price: 3500,
    rating: 4.85,
    reviews: 250,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Kitchenette', 'Air conditioning', 'TV'],
    host: {
      name: 'Aditi',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: true,
    },
    images: [
        'https://picsum.photos/seed/49/800/600',
        'https://picsum.photos/seed/50/800/600',
        'https://picsum.photos/seed/51/800/600',
        'https://picsum.photos/seed/52/800/600',
        'https://picsum.photos/seed/53/800/600',
        'https://picsum.photos/seed/54/800/600',
    ],
    details: 'A stylish and modern studio apartment in Pune\'s most upscale neighborhood, Koregaon Park. The studio is cleverly designed to maximize space and comfort. You are surrounded by the city\'s best restaurants, bars, and boutiques. It is a perfect spot for solo travelers or couples.',
    summary: 'A stylish, modern studio in upscale Koregaon Park, Pune, surrounded by top restaurants and shops, perfect for solo travelers or couples.'
  },
  {
    id: '10',
    title: 'Luxury Apartment in Juhu',
    type: 'Entire apartment',
    location: 'Mumbai, India',
    coords: { lat: 19.10, lng: 72.83 },
    price: 9500,
    rating: 4.9,
    reviews: 130,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Pool', 'Gym'],
    host: {
      name: 'Anjali',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: true,
    },
    images: [
        'https://picsum.photos/seed/55/800/600',
        'https://picsum.photos/seed/56/800/600',
        'https://picsum.photos/seed/57/800/600',
        'https://picsum.photos/seed/58/800/600',
        'https://picsum.photos/seed/59/800/600',
        'https://picsum.photos/seed/60/800/600',
    ],
    details: 'A luxurious apartment in the star-studded neighborhood of Juhu. The building offers excellent amenities including a swimming pool and gym. The apartment is elegantly furnished and offers views of the city. A short walk to Juhu Beach and Prithvi Theatre.',
    summary: 'A luxurious, elegantly furnished apartment in Juhu with city views, a pool, and a gym, just a short walk from Juhu Beach and Prithvi Theatre.'
  },
  {
    id: '11',
    title: 'Designer Duplex in Hauz Khas Village',
    type: 'Entire loft',
    location: 'Delhi, India',
    coords: { lat: 28.55, lng: 77.19 },
    price: 7000,
    rating: 4.88,
    reviews: 160,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Lake view', 'Terrace'],
    host: {
      name: 'Arjun',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: true,
    },
    images: [
        'https://picsum.photos/seed/61/800/600',
        'https://picsum.photos/seed/62/800/600',
        'https://picsum.photos/seed/63/800/600',
        'https://picsum.photos/seed/64/800/600',
        'https://picsum.photos/seed/65/800/600',
        'https://picsum.photos/seed/66/800/600',
    ],
    details: 'A stunning designer duplex in the heart of Delhi\'s creative hub, Hauz Khas Village. The loft offers beautiful views of the lake and historic ruins. It features a private terrace, modern art, and a fully equipped kitchen. Explore the adjacent deer park, art galleries, and chic cafes.',
    summary: 'A stunning designer duplex in Hauz Khas Village with lake and ruins views, a private terrace, modern art, and a full kitchen, near a deer park and cafes.'
  },
  {
    id: '12',
    title: 'Garden Bungalow in Indiranagar',
    type: 'Entire bungalow',
    location: 'Bengaluru, India',
    coords: { lat: 12.97, lng: 77.64 },
    price: 9000,
    rating: 4.92,
    reviews: 200,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Garden', 'Free parking'],
    host: {
      name: 'Sunita',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: true,
    },
    images: [
        'https://picsum.photos/seed/67/800/600',
        'https://picsum.photos/seed/68/800/600',
        'https://picsum.photos/seed/69/800/600',
        'https://picsum.photos/seed/70/800/600',
        'https://picsum.photos/seed/71/800/600',
        'https://picsum.photos/seed/72/800/600',
    ],
    details: 'A charming garden bungalow in the lively Indiranagar neighborhood. The house is surrounded by a beautiful garden, offering a quiet escape in the city. It is spacious and well-furnished. You are a short walk from some of Bengaluru\'s best pubs, restaurants, and shops.',
    summary: 'A charming, spacious garden bungalow in lively Indiranagar, offering a quiet escape with easy access to top pubs, restaurants, and shops.'
  },
  {
    id: '13',
    title: 'Beach House on ECR',
    type: 'Entire house',
    location: 'Chennai, India',
    coords: { lat: 12.8, lng: 80.25 },
    price: 18000,
    rating: 4.85,
    reviews: 140,
    guests: 10,
    bedrooms: 4,
    beds: 5,
    baths: 4,
    amenities: ['Wifi', 'Kitchen', 'Pool', 'Air conditioning', 'Beachfront'],
    host: {
      name: 'Rajesh',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: false,
    },
    images: [
        'https://picsum.photos/seed/73/800/600',
        'https://picsum.photos/seed/74/800/600',
        'https://picsum.photos/seed/75/800/600',
        'https://picsum.photos/seed/76/800/600',
        'https://picsum.photos/seed/77/800/600',
        'https://picsum.photos/seed/78/800/600',
    ],
    details: 'A sprawling beach house on the East Coast Road, perfect for large groups and celebrations. The property has direct access to a private beach area and a large swimming pool. Enjoy the sea breeze from the spacious balconies. It\'s a great weekend getaway from the city.',
    summary: 'A large ECR beach house with private beach access and a pool, perfect for group getaways with spacious balconies and sea views.'
  },
  {
    id: '14',
    title: 'Boutique Stay in Candolim',
    type: 'Private room in boutique hotel',
    location: 'Goa, India',
    coords: { lat: 15.52, lng: 73.76 },
    price: 6000,
    rating: 4.9,
    reviews: 220,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Pool', 'Air conditioning', 'Breakfast included', 'Bar'],
    host: {
      name: 'Sanjay',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: true,
    },
    images: [
        'https://picsum.photos/seed/79/800/600',
        'https://picsum.photos/seed/80/800/600',
        'https://picsum.photos/seed/81/800/600',
        'https://picsum.photos/seed/82/800/600',
        'https://picsum.photos/seed/83/800/600',
        'https://picsum.photos/seed/84/800/600',
    ],
    details: 'A stylish room in a chic boutique hotel in Candolim, North Goa. The hotel has a beautiful swimming pool and a lively bar. Your room is tastefully decorated and has a private balcony. Located close to the beach and some of Goa\'s most popular restaurants and nightlife spots.',
      summary: 'Stylish room in a chic Candolim boutique hotel with a pool, bar, and private balcony, near the beach and popular nightlife.'
  },
  {
    id: '15',
    title: 'Artist\'s Studio near Amber Fort',
    type: 'Entire studio',
    location: 'Jaipur, India',
    coords: { lat: 26.98, lng: 75.85 },
    price: 3000,
    rating: 4.78,
    reviews: 180,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Kitchenette', 'Air conditioning', 'Fort view'],
    host: {
      name: 'Meera',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: false,
    },
    images: [
        'https://picsum.photos/seed/85/800/600',
        'https://picsum.photos/seed/86/800/600',
        'https://picsum.photos/seed/87/800/600',
        'https://picsum.photos/seed/88/800/600',
        'https://picsum.photos/seed/89/800/600',
        'https://picsum.photos/seed/90/800/600',
    ],
    details: 'A cozy studio apartment with stunning views of the Amber Fort. The studio is owned by a local artist and is filled with her work. It has a small kitchenette and a lovely terrace to enjoy the views. It\'s a perfect base for exploring the historic forts of Jaipur.',
    summary: 'A cozy artist\'s studio with stunning Amber Fort views, a kitchenette, and a terrace, perfect for exploring Jaipur\'s historic forts.'
  },
  {
    id: '16',
    title: 'Lakeside Palace View Room',
    type: 'Private room in palace',
    location: 'Udaipur, India',
    coords: { lat: 24.5854, lng: 73.7125 },
    price: 13000,
    rating: 4.97,
    reviews: 250,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Pool', 'Air conditioning', 'Lake view', 'Restaurant'],
    host: {
      name: 'Rana',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: true,
    },
    images: [
        'https://picsum.photos/seed/91/800/600',
        'https://picsum.photos/seed/92/800/600',
        'https://picsum.photos/seed/93/800/600',
        'https://picsum.photos/seed/94/800/600',
        'https://picsum.photos/seed/95/800/600',
        'https://picsum.photos/seed/96/800/600',
    ],
    details: 'Stay in a real palace overlooking Lake Pichola. This room offers breathtaking views of the lake and the City Palace. Enjoy royal treatment, dine in magnificent halls, and take a boat ride on the lake directly from the palace.',
    summary: 'A room in a palace on Lake Pichola with stunning views of the lake and City Palace, offering royal treatment and boat rides.'
  },
  {
    id: '17',
    title: 'Tea Estate Bungalow',
    type: 'Entire bungalow',
    location: 'Munnar, India',
    coords: { lat: 10.0889, lng: 77.0595 },
    price: 10000,
    rating: 4.95,
    reviews: 180,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    amenities: ['Wifi', 'Kitchen', 'Fireplace', 'Garden', 'Mountain view'],
    host: {
      name: 'Thomas',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: true,
    },
    images: [
        'https://picsum.photos/seed/97/800/600',
        'https://picsum.photos/seed/98/800/600',
        'https://picsum.photos/seed/99/800/600',
        'https://picsum.photos/seed/100/800/600',
        'https://picsum.photos/seed/101/800/600',
        'https://picsum.photos/seed/102/800/600',
    ],
    details: 'Wake up to the smell of fresh tea leaves in this colonial-era bungalow set amidst a sprawling tea estate in Munnar. Enjoy guided tea plantation walks, trekking in the nearby hills, and cozy evenings by the fireplace.',
    summary: 'A colonial-era bungalow on a Munnar tea estate with guided walks, trekking, and cozy fireplaces.'
  },
  {
    id: '18',
    title: 'French Quarter Townhouse',
    type: 'Entire townhouse',
    location: 'Pondicherry, India',
    coords: { lat: 11.9139, lng: 79.8145 },
    price: 7500,
    rating: 4.89,
    reviews: 210,
    guests: 5,
    bedrooms: 2,
    beds: 3,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Balcony', 'Courtyard'],
    host: {
      name: 'Jean-Pierre',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: true,
    },
    images: [
        'https://picsum.photos/seed/103/800/600',
        'https://picsum.photos/seed/104/800/600',
        'https://picsum.photos/seed/105/800/600',
        'https://picsum.photos/seed/106/800/600',
        'https://picsum.photos/seed/107/800/600',
        'https://picsum.photos/seed/108/800/600',
    ],
    details: 'Experience the unique Franco-Tamil culture of Pondicherry in this beautiful townhouse in the White Town. The house is full of character, with high ceilings, colorful walls, and a quiet inner courtyard. Walk to the Promenade Beach and explore the charming French Quarter.',
    summary: 'A characterful townhouse in Pondicherry\'s White Town, featuring high ceilings, colorful walls, a courtyard, and a short walk to the beach.'
  },
  {
    id: '19',
    title: 'Luxury Houseboat on Dal Lake',
    type: 'Private room in boat',
    location: 'Srinagar, India',
    coords: { lat: 34.0837, lng: 74.7973 },
    price: 12000,
    rating: 4.98,
    reviews: 300,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Meals included', 'Lake view', 'Veranda'],
    host: {
      name: 'Yusuf',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: true,
    },
    images: [
        'https://picsum.photos/seed/109/800/600',
        'https://picsum.photos/seed/110/800/600',
        'https://picsum.photos/seed/111/800/600',
        'https://picsum.photos/seed/112/800/600',
        'https://picsum.photos/seed/113/800/600',
        'https://picsum.photos/seed/114/800/600',
    ],
    details: 'An unforgettable experience awaits you on this luxurious houseboat on Dal Lake. The boat is intricately carved from cedar wood and features traditional Kashmiri carpets and furniture. Enjoy stunning views of the Himalayas, delicious home-cooked Kashmiri food, and a personal shikara ride.',
    summary: 'A luxurious houseboat on Dal Lake with Himalayan views, offering traditional Kashmiri decor, home-cooked meals, and a personal shikara ride.'
  },
  {
    id: '20',
    title: 'Corporate Studio in Gurgaon',
    type: 'Entire studio',
    location: 'Delhi, India',
    coords: { lat: 28.4595, lng: 77.0266 },
    price: 4000,
    rating: 4.75,
    reviews: 150,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Kitchenette', 'Air conditioning', 'Gym', 'Workspace'],
    host: {
      name: 'Sahil',
      avatar: 'https://picsum.photos/100/100',
      isSuperhost: false,
    },
    images: [
        'https://picsum.photos/seed/115/800/600',
        'https://picsum.photos/seed/116/800/600',
        'https://picsum.photos/seed/117/800/600',
        'https://picsum.photos/seed/118/800/600',
        'https://picsum.photos/seed/119/800/600',
        'https://picsum.photos/seed/120/800/600',
    ],
    details: 'A modern and efficient studio in the business hub of Gurgaon. Perfect for corporate travelers, this studio comes with a dedicated workspace, high-speed internet, and access to a gym. It is well-connected by metro and close to major corporate parks and shopping malls.',
    summary: 'A modern studio in Gurgaon\'s business hub with a dedicated workspace, high-speed internet, and a gym, perfect for corporate travelers.'
  },
  // Add 6 more for Mumbai
  {
    id: '21',
    title: 'Cozy Studio in Powai',
    type: 'Entire studio',
    location: 'Mumbai, India',
    coords: { lat: 19.1176, lng: 72.9060 },
    price: 4500,
    rating: 4.7,
    reviews: 110,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Kitchenette', 'Air conditioning', 'TV'],
    host: { name: 'Priya', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/121/800/600', 'https://picsum.photos/seed/122/800/600'],
    details: 'A comfortable studio in the vibrant neighborhood of Powai, close to the lake. Ideal for students and professionals.',
    summary: 'A cozy and affordable studio apartment in Powai, Mumbai, perfect for students and professionals visiting the area.'
  },
  {
    id: '22',
    title: 'Art Deco Flat in South Mumbai',
    type: 'Entire apartment',
    location: 'Mumbai, India',
    coords: { lat: 18.9220, lng: 72.8311 },
    price: 11000,
    rating: 4.95,
    reviews: 90,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'TV', 'Elevator'],
    host: { name: 'Farhan', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/123/800/600', 'https://picsum.photos/seed/124/800/600'],
    details: 'Charming Art Deco apartment in a heritage building in Colaba. Walking distance to Gateway of India and art galleries.',
    summary: 'A beautiful Art Deco apartment in a heritage building in South Mumbai, close to major landmarks.'
  },
  {
    id: '23',
    title: 'Modern High-Rise with City Views',
    type: 'Entire apartment',
    location: 'Mumbai, India',
    coords: { lat: 19.0176, lng: 72.8562 },
    price: 15000,
    rating: 4.88,
    reviews: 75,
    guests: 5,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Pool', 'Gym', 'Parking'],
    host: { name: 'Siddharth', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/125/800/600', 'https://picsum.photos/seed/126/800/600'],
    details: 'Stay in a modern high-rise in Lower Parel, the new financial hub. Enjoy stunning city views and top-notch amenities.',
    summary: 'A luxurious apartment in a modern Lower Parel high-rise, featuring spectacular city views and premium amenities.'
  },
  {
    id: '24',
    title: 'Bungalow in a Quiet Lane',
    type: 'Entire bungalow',
    location: 'Mumbai, India',
    coords: { lat: 19.1332, lng: 72.8265 },
    price: 25000,
    rating: 4.98,
    reviews: 125,
    guests: 8,
    bedrooms: 4,
    beds: 4,
    baths: 4,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Garden', 'Parking'],
    host: { name: 'Karan', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/127/800/600', 'https://picsum.photos/seed/128/800/600'],
    details: 'A rare find in Mumbai, this spacious bungalow in a quiet lane of Andheri offers a peaceful retreat with a private garden.',
    summary: 'A serene and spacious bungalow with a private garden, located in a quiet lane in the bustling city of Mumbai.'
  },
  {
    id: '25',
    title: 'Penthouse with Private Terrace',
    type: 'Entire penthouse',
    location: 'Mumbai, India',
    coords: { lat: 19.2288, lng: 72.8540 },
    price: 20000,
    rating: 4.92,
    reviews: 80,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Terrace', 'Jacuzzi'],
    host: { name: 'Natasha', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/129/800/600', 'https://picsum.photos/seed/130/800/600'],
    details: 'A stunning penthouse in Borivali with a large private terrace and a jacuzzi. Perfect for a luxurious staycation.',
    summary: 'An exquisite penthouse in Mumbai, featuring a large private terrace and a jacuzzi for the ultimate luxury stay.'
  },
  {
    id: '26',
    title: 'Budget Room near Airport',
    type: 'Private room',
    location: 'Mumbai, India',
    coords: { lat: 19.0896, lng: 72.8777 },
    price: 3000,
    rating: 4.6,
    reviews: 300,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Air conditioning'],
    host: { name: 'Suresh', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/131/800/600', 'https://picsum.photos/seed/132/800/600'],
    details: 'A clean and comfortable private room with an attached bathroom, located very close to the Mumbai airport. Ideal for transit passengers.',
    summary: 'A convenient and clean private room with an attached bathroom, situated near the Mumbai airport.'
  },
  // Add 5 more for Delhi
  {
    id: '27',
    title: 'Lutyens Zone Bungalow',
    type: 'Entire bungalow',
    location: 'Delhi, India',
    coords: { lat: 28.6139, lng: 77.2090 },
    price: 35000,
    rating: 5.0,
    reviews: 50,
    guests: 10,
    bedrooms: 5,
    beds: 5,
    baths: 5,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Garden', 'Pool'],
    host: { name: 'Mr. Singh', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/133/800/600', 'https://picsum.photos/seed/134/800/600'],
    details: 'An exclusive colonial bungalow in the heart of Lutyens\' Delhi. Experience unparalleled luxury and privacy.',
    summary: 'An opulent colonial bungalow offering supreme luxury and privacy in the prestigious Lutyens\' Delhi.'
  },
  {
    id: '28',
    title: 'Penthouse with Qutub Minar View',
    type: 'Entire penthouse',
    location: 'Delhi, India',
    coords: { lat: 28.5245, lng: 77.1855 },
    price: 18000,
    rating: 4.95,
    reviews: 85,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Terrace', 'Monument view'],
    host: { name: 'Deepika', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/135/800/600', 'https://picsum.photos/seed/136/800/600'],
    details: 'A beautiful penthouse in Mehrauli with a direct, stunning view of the Qutub Minar from its private terrace.',
    summary: 'A gorgeous penthouse in Delhi with a private terrace offering stunning, direct views of the Qutub Minar.'
  },
  {
    id: '29',
    title: 'Farmhouse Retreat',
    type: 'Entire farmhouse',
    location: 'Delhi, India',
    coords: { lat: 28.4744, lng: 77.0845 },
    price: 22000,
    rating: 4.9,
    reviews: 120,
    guests: 12,
    bedrooms: 4,
    beds: 6,
    baths: 4,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Pool', 'Lawn'],
    host: { name: 'Rakesh', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/137/800/600', 'https://picsum.photos/seed/138/800/600'],
    details: 'A sprawling farmhouse on the outskirts of Delhi, perfect for parties and weekend getaways. Comes with a private pool and a massive lawn.',
    summary: 'A large farmhouse on the outskirts of Delhi, perfect for events with its private pool and expansive lawn.'
  },
  {
    id: '30',
    title: 'GK2 Rooftop Studio',
    type: 'Entire studio',
    location: 'Delhi, India',
    coords: { lat: 28.5355, lng: 77.2415 },
    price: 5000,
    rating: 4.8,
    reviews: 200,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Kitchenette', 'Air conditioning', 'Terrace'],
    host: { name: 'Neha', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/139/800/600', 'https://picsum.photos/seed/140/800/600'],
    details: 'A private rooftop studio with a terrace in the posh Greater Kailash 2. Close to the M-Block market.',
    summary: 'A private rooftop studio with a terrace in Greater Kailash 2, conveniently located near the M-Block market.'
  },
  {
    id: '31',
    title: 'Connaught Place Apartment',
    type: 'Entire apartment',
    location: 'Delhi, India',
    coords: { lat: 28.6315, lng: 77.2167 },
    price: 8000,
    rating: 4.85,
    reviews: 150,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'TV'],
    host: { name: 'Rajiv', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/141/800/600', 'https://picsum.photos/seed/142/800/600'],
    details: 'A well-furnished apartment right in the heart of the city, Connaught Place. Everything you need is just a walk away.',
    summary: 'A well-furnished apartment in the heart of Connaught Place, with all amenities within walking distance.'
  },
  // Add 6 more for Bengaluru
  {
    id: '32',
    title: 'Koramangala Social Hub',
    type: 'Private room',
    location: 'Bengaluru, India',
    coords: { lat: 12.9352, lng: 77.6245 },
    price: 3000,
    rating: 4.8,
    reviews: 400,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Air conditioning', 'Shared kitchen', 'Coworking space'],
    host: { name: 'Sandeep', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/143/800/600', 'https://picsum.photos/seed/144/800/600'],
    details: 'A vibrant private room in a co-living space in the heart of Koramangala. Perfect for digital nomads and young professionals.',
    summary: 'A lively private room in a Koramangala co-living space, ideal for digital nomads and professionals.'
  },
  {
    id: '33',
    title: 'Whitefield Luxury Villa',
    type: 'Entire villa',
    location: 'Bengaluru, India',
    coords: { lat: 12.9698, lng: 77.7499 },
    price: 18000,
    rating: 4.9,
    reviews: 150,
    guests: 10,
    bedrooms: 4,
    beds: 5,
    baths: 4,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Pool', 'Garden'],
    host: { name: 'Anand', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/145/800/600', 'https://picsum.photos/seed/146/800/600'],
    details: 'A luxurious villa in the IT hub of Whitefield. Comes with a private pool and a beautiful garden. Perfect for families.',
    summary: 'A luxurious villa in Whitefield with a private pool and garden, ideal for families seeking a premium stay.'
  },
  {
    id: '34',
    title: 'Traditional House in Malleswaram',
    type: 'Entire house',
    location: 'Bengaluru, India',
    coords: { lat: 13.0068, lng: 77.5694 },
    price: 7000,
    rating: 4.88,
    reviews: 250,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Garden'],
    host: { name: 'Shanti', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/147/800/600', 'https://picsum.photos/seed/148/800/600'],
    details: 'Experience old Bangalore in this charming traditional house in Malleswaram, known for its temples and traditional eateries.',
    summary: 'A charming, traditional house in Malleswaram, offering a taste of old Bangalore with its temples and classic eateries.'
  },
  {
    id: '35',
    title: 'Serviced Apartment in HSR Layout',
    type: 'Entire apartment',
    location: 'Bengaluru, India',
    coords: { lat: 12.9121, lng: 77.6446 },
    price: 5000,
    rating: 4.7,
    reviews: 300,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Daily housekeeping'],
    host: { name: 'Corporate Stays', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/149/800/600', 'https://picsum.photos/seed/150/800/600'],
    details: 'A fully serviced 2BHK apartment in HSR Layout, perfect for business travelers. Close to many tech parks.',
    summary: 'A fully serviced 2BHK apartment in HSR Layout, ideal for business travelers and close to major tech parks.'
  },
  {
    id: '36',
    title: 'Budget Stay in Electronic City',
    type: 'Private room',
    location: 'Bengaluru, India',
    coords: { lat: 12.8452, lng: 77.6602 },
    price: 2500,
    rating: 4.6,
    reviews: 500,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Air conditioning'],
    host: { name: 'Ravi', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/151/800/600', 'https://picsum.photos/seed/152/800/600'],
    details: 'A clean, basic, and affordable room in Electronic City, very close to Infosys and Wipro campuses.',
    summary: 'A clean, affordable room in Electronic City, conveniently located near Infosys and Wipro.'
  },
  {
    id: '37',
    title: 'Penthouse with 360° Views',
    type: 'Entire penthouse',
    location: 'Bengaluru, India',
    coords: { lat: 12.9716, lng: 77.5946 },
    price: 25000,
    rating: 5.0,
    reviews: 60,
    guests: 8,
    bedrooms: 4,
    beds: 4,
    baths: 4,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Pool', 'Terrace'],
    host: { name: 'Aarav', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/153/800/600', 'https://picsum.photos/seed/154/800/600'],
    details: 'A super luxurious penthouse in central Bangalore with 360-degree views of the city. Comes with a private rooftop pool.',
    summary: 'A lavish penthouse in central Bangalore with a private rooftop pool and 360-degree city views.'
  },
  // Add 6 more for Chennai
  {
    id: '38',
    title: 'Seafront Villa on ECR',
    type: 'Entire villa',
    location: 'Chennai, India',
    coords: { lat: 12.85, lng: 80.25 },
    price: 20000,
    rating: 4.9,
    reviews: 100,
    guests: 10,
    bedrooms: 4,
    beds: 5,
    baths: 4,
    amenities: ['Wifi', 'Kitchen', 'Pool', 'Air conditioning', 'Beachfront'],
    host: { name: 'Kumar', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/155/800/600', 'https://picsum.photos/seed/156/800/600'],
    details: 'A beautiful seafront villa on the East Coast Road with a private pool and direct beach access. Close to Mahabalipuram.',
    summary: 'A beautiful seafront villa on the East Coast Road with a private pool and direct beach access, close to Mahabalipuram.'
  },
  {
    id: '39',
    title: 'Poes Garden Luxury Apartment',
    type: 'Entire apartment',
    location: 'Chennai, India',
    coords: { lat: 13.0475, lng: 80.2505 },
    price: 15000,
    rating: 4.95,
    reviews: 80,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Gym'],
    host: { name: 'Selva', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/157/800/600', 'https://picsum.photos/seed/158/800/600'],
    details: 'An ultra-luxurious apartment in the most exclusive neighborhood of Chennai, Poes Garden. Impeccable service and amenities.',
    summary: 'An ultra-luxurious apartment in Chennai\'s exclusive Poes Garden, offering impeccable service and amenities.'
  },
  {
    id: '40',
    title: 'Art-filled apartment in Nungambakkam',
    type: 'Entire apartment',
    location: 'Chennai, India',
    coords: { lat: 13.0622, lng: 80.2405 },
    price: 7000,
    rating: 4.85,
    reviews: 150,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'TV'],
    host: { name: 'Lakshmi', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/159/800/600', 'https://picsum.photos/seed/160/800/600'],
    details: 'A quirky and colorful apartment filled with modern art, located in the heart of Nungambakkam. Close to cafes and cultural spots.',
    summary: 'A vibrant, art-filled apartment in the heart of Nungambakkam, near cafes and cultural attractions.'
  },
  {
    id: '41',
    title: 'Adyar River View Room',
    type: 'Private room',
    location: 'Chennai, India',
    coords: { lat: 13.0076, lng: 80.2526 },
    price: 3500,
    rating: 4.7,
    reviews: 200,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Air conditioning', 'River view'],
    host: { name: 'Ganesh', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/161/800/600', 'https://picsum.photos/seed/162/800/600'],
    details: 'A simple, clean room in a large house with a beautiful view of the Adyar River. Close to the Theosophical Society.',
    summary: 'A clean, simple room with a scenic Adyar River view, conveniently located near the Theosophical Society.'
  },
  {
    id: '42',
    title: 'IT Corridor Serviced Apt',
    type: 'Entire apartment',
    location: 'Chennai, India',
    coords: { lat: 12.908, lng: 80.221 },
    price: 4500,
    rating: 4.65,
    reviews: 250,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    amenities: ['Wifi', 'Kitchenette', 'Air conditioning', 'Gym'],
    host: { name: 'OMR Stays', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/163/800/600', 'https://picsum.photos/seed/164/800/600'],
    details: 'A serviced apartment on OMR, the IT corridor of Chennai. Ideal for those traveling for work.',
    summary: 'A serviced apartment on OMR in Chennai, perfect for business travelers working in the IT corridor.'
  },
  {
    id: '43',
    title: 'Besant Nagar Beach House',
    type: 'Entire house',
    location: 'Chennai, India',
    coords: { lat: 13.0006, lng: 80.2655 },
    price: 12000,
    rating: 4.9,
    reviews: 180,
    guests: 8,
    bedrooms: 3,
    beds: 4,
    baths: 3,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Terrace', 'Beach proximity'],
    host: { name: 'Murali', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/165/800/600', 'https://picsum.photos/seed/166/800/600'],
    details: 'A spacious house just a street away from the popular Elliot\'s Beach in Besant Nagar. Surrounded by great food joints.',
    summary: 'A spacious house near Elliot\'s Beach in Besant Nagar, surrounded by excellent dining options.'
  },
  // Add 6 more for Goa
  {
    id: '44',
    title: 'Anjuna Flea Market Pad',
    type: 'Private room',
    location: 'Goa, India',
    coords: { lat: 15.58, lng: 73.74 },
    price: 2500,
    rating: 4.7,
    reviews: 450,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Air conditioning', 'Pool'],
    host: { name: 'Shiva', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/167/800/600', 'https://picsum.photos/seed/168/800/600'],
    details: 'A basic but cool room in a guesthouse right next to the famous Anjuna Flea Market. Dive into the hippie culture.',
    summary: 'A cool, basic guesthouse room next to the Anjuna Flea Market, perfect for experiencing the local hippie culture.'
  },
  {
    id: '45',
    title: 'Palolem Beach Hut',
    type: 'Entire hut',
    location: 'Goa, India',
    coords: { lat: 15.01, lng: 74.02 },
    price: 4000,
    rating: 4.8,
    reviews: 350,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Air conditioning', 'Beachfront', 'Restaurant'],
    host: { name: 'Pedro', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/169/800/600', 'https://picsum.photos/seed/170/800/600'],
    details: 'A classic Goan beach hut on the beautiful Palolem beach in South Goa. Wake up to the sound of waves.',
    summary: 'A classic Goan beach hut on Palolem beach in South Goa, where you can wake up to the sound of waves.'
  },
  {
    id: '46',
    title: 'Ashwem Yoga Retreat',
    type: 'Private room',
    location: 'Goa, India',
    coords: { lat: 15.65, lng: 73.72 },
    price: 5000,
    rating: 4.9,
    reviews: 200,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Air conditioning', 'Pool', 'Yoga classes', 'Vegan food'],
    host: { name: 'Anya', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/171/800/600', 'https://picsum.photos/seed/172/800/600'],
    details: 'A peaceful room in a yoga retreat near Ashwem beach. Daily yoga classes and healthy vegan food available.',
    summary: 'A serene room in a yoga retreat near Ashwem beach, offering daily yoga and healthy vegan meals.'
  },
  {
    id: '47',
    title: 'Panjim Fontainhas Studio',
    type: 'Entire studio',
    location: 'Goa, India',
    coords: { lat: 15.49, lng: 73.82 },
    price: 4500,
    rating: 4.85,
    reviews: 180,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Air conditioning', 'Kitchenette'],
    host: { name: 'Fernandes', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/173/800/600', 'https://picsum.photos/seed/174/800/600'],
    details: 'A cute studio in the colourful Latin Quarter of Panjim (Fontainhas). Explore the unique architecture and cafes.',
    summary: 'A charming studio in Fontainhas, Panjim\'s colorful Latin Quarter, perfect for exploring unique architecture and cafes.'
  },
  {
    id: '48',
    title: 'Vagator Hilltop Villa',
    type: 'Entire villa',
    location: 'Goa, India',
    coords: { lat: 15.60, lng: 73.74 },
    price: 25000,
    rating: 4.95,
    reviews: 100,
    guests: 8,
    bedrooms: 4,
    beds: 4,
    baths: 4,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Pool', 'Sea view'],
    host: { name: 'Vikrant', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/175/800/600', 'https://picsum.photos/seed/176/800/600'],
    details: 'A stunning villa on a hilltop in Vagator, offering panoramic views of the sea. Close to famous clubs and restaurants.',
    summary: 'A stunning hilltop villa in Vagator with panoramic sea views, located near famous clubs and restaurants.'
  },
  {
    id: '49',
    title: 'Mandovi River-View Apartment',
    type: 'Entire apartment',
    location: 'Goa, India',
    coords: { lat: 15.50, lng: 73.83 },
    price: 9000,
    rating: 4.8,
    reviews: 130,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Pool', 'River view'],
    host: { name: 'Saldanha', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/177/800/600', 'https://picsum.photos/seed/178/800/600'],
    details: 'A modern apartment in a high-rise with beautiful views of the Mandovi river. Close to Panjim and the casinos.',
    summary: 'A modern high-rise apartment with beautiful Mandovi river views, conveniently located near Panjim and the casinos.'
  },
  // Add 6 more for Jaipur
  {
    id: '50',
    title: 'C-Scheme Boutique Hotel',
    type: 'Private room in hotel',
    location: 'Jaipur, India',
    coords: { lat: 26.90, lng: 75.80 },
    price: 7000,
    rating: 4.9,
    reviews: 250,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Pool', 'Air conditioning', 'Restaurant', 'Gym'],
    host: { name: 'The Raj Palace', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/179/800/600', 'https://picsum.photos/seed/180/800/600'],
    details: 'A luxurious room in a modern boutique hotel in the upscale C-Scheme area. Close to shopping and fine dining.',
    summary: 'A luxurious room in a modern C-Scheme boutique hotel, near upscale shopping and fine dining.'
  },
  {
    id: '51',
    title: 'Homestay with a Local Family',
    type: 'Private room in house',
    location: 'Jaipur, India',
    coords: { lat: 26.88, lng: 75.79 },
    price: 2500,
    rating: 4.95,
    reviews: 400,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Air conditioning', 'Home-cooked meals'],
    host: { name: 'Sharma Family', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/181/800/600', 'https://picsum.photos/seed/182/800/600'],
    details: 'Experience true Rajasthani hospitality by staying with a local family in their home in Civil Lines. Enjoy delicious home-cooked meals.',
    summary: 'Experience authentic Rajasthani hospitality and delicious home-cooked meals at a family homestay in Civil Lines.'
  },
  {
    id: '52',
    title: 'Pink City Wall Apartment',
    type: 'Entire apartment',
    location: 'Jaipur, India',
    coords: { lat: 26.92, lng: 75.82 },
    price: 4500,
    rating: 4.8,
    reviews: 220,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning'],
    host: { name: 'Pankaj', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/183/800/600', 'https://picsum.photos/seed/184/800/600'],
    details: 'A simple apartment located right inside the walled city of Jaipur. Explore the bazaars and culture on foot.',
    summary: 'A simple apartment in Jaipur\'s walled city, perfect for exploring the local bazaars and culture on foot.'
  },
  {
    id: '53',
    title: 'Vaishali Nagar Modern Home',
    type: 'Entire house',
    location: 'Jaipur, India',
    coords: { lat: 26.91, lng: 75.74 },
    price: 10000,
    rating: 4.88,
    reviews: 120,
    guests: 8,
    bedrooms: 3,
    beds: 4,
    baths: 3,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Parking'],
    host: { name: 'Sunita', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/185/800/600', 'https://picsum.photos/seed/186/800/600'],
    details: 'A modern and spacious house in the residential area of Vaishali Nagar. Good for families and long stays.',
    summary: 'A modern, spacious house in Vaishali Nagar, ideal for families and extended stays.'
  },
  {
    id: '54',
    title: 'Eco-friendly Farm Stay',
    type: 'Entire cottage',
    location: 'Jaipur, India',
    coords: { lat: 27.05, lng: 75.80 },
    price: 6000,
    rating: 4.95,
    reviews: 180,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    amenities: ['Organic meals', 'Farm animals', 'Peaceful'],
    host: { name: 'Devika', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/187/800/600', 'https://picsum.photos/seed/188/800/600'],
    details: 'An eco-friendly cottage on a farm on the outskirts of Jaipur. Enjoy fresh organic meals and a peaceful environment.',
    summary: 'An eco-friendly farm cottage outside Jaipur, offering organic meals and a tranquil setting.'
  },
  {
    id: '55',
    title: 'Backpacker Hostel near Station',
    type: 'Shared dorm',
    location: 'Jaipur, India',
    coords: { lat: 26.92, lng: 75.78 },
    price: 800,
    rating: 4.7,
    reviews: 600,
    guests: 1,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Shared kitchen', 'Lockers', 'Common area'],
    host: { name: 'Zostel', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/189/800/600', 'https://picsum.photos/seed/190/800/600'],
    details: 'A lively backpacker hostel close to the Jaipur railway station. Meet fellow travelers and explore the city on a budget.',
    summary: 'A vibrant backpacker hostel near Jaipur railway station, ideal for budget travelers looking to connect with others.'
  },
  // Add 7 more for Kolkata
  {
    id: '56',
    title: 'Park Street Penthouse',
    type: 'Entire penthouse',
    location: 'Kolkata, India',
    coords: { lat: 22.55, lng: 88.35 },
    price: 12000,
    rating: 4.9,
    reviews: 90,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Terrace'],
    host: { name: 'Roy', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/191/800/600', 'https://picsum.photos/seed/192/800/600'],
    details: 'A luxurious penthouse on Park Street, the heart of Kolkata\'s dining and nightlife scene. Enjoy city views from your private terrace.',
    summary: 'A luxurious Park Street penthouse with a private terrace and city views, in the heart of Kolkata\'s dining and nightlife.'
  },
  {
    id: '57',
    title: 'Salt Lake Modern Apartment',
    type: 'Entire apartment',
    location: 'Kolkata, India',
    coords: { lat: 22.58, lng: 88.40 },
    price: 6000,
    rating: 4.8,
    reviews: 150,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'TV'],
    host: { name: 'Deb', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/193/800/600', 'https://picsum.photos/seed/194/800/600'],
    details: 'A modern and clean apartment in the planned township of Salt Lake. Ideal for business travelers and families.',
    summary: 'A clean, modern apartment in Salt Lake, perfect for business travelers and families.'
  },
  {
    id: '58',
    title: 'Hooghly River View Flat',
    type: 'Entire apartment',
    location: 'Kolkata, India',
    coords: { lat: 22.59, lng: 88.34 },
    price: 8000,
    rating: 4.85,
    reviews: 120,
    guests: 5,
    bedrooms: 2,
    beds: 3,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'River view'],
    host: { name: 'Banerjee', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/195/800/600', 'https://picsum.photos/seed/196/800/600'],
    details: 'An apartment with a serene view of the Hooghly river. Watch the boats go by from your balcony. Away from the city chaos.',
    summary: 'A tranquil apartment with a serene Hooghly river view and a balcony, perfect for escaping the city\'s chaos.'
  },
  {
    id: '59',
    title: 'Gariahat Shopping Paradise',
    type: 'Private room',
    location: 'Kolkata, India',
    coords: { lat: 22.51, lng: 88.36 },
    price: 2500,
    rating: 4.7,
    reviews: 250,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Air conditioning'],
    host: { name: 'Mrs. Das', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/197/800/600', 'https://picsum.photos/seed/198/800/600'],
    details: 'A private room in a house right in the middle of Gariahat, Kolkata\'s shopping hub. Perfect for shopaholics.',
    summary: 'A private room in a Gariahat house, perfect for shoppers in the heart of Kolkata\'s shopping district.'
  },
  {
    id: '60',
    title: 'New Town Techie Studio',
    type: 'Entire studio',
    location: 'Kolkata, India',
    coords: { lat: 22.57, lng: 88.47 },
    price: 3500,
    rating: 4.75,
    reviews: 180,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Kitchenette', 'Air conditioning', 'Gym'],
    host: { name: 'Rohan', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/199/800/600', 'https://picsum.photos/seed/200/800/600'],
    details: 'A compact studio in New Town, close to the IT parks. Has all modern amenities for a comfortable stay.',
    summary: 'A compact, modern studio in New Town with all amenities, ideal for a comfortable stay near the IT parks.'
  },
  {
    id: '61',
    title: 'Ballygunge Ancestral Home',
    type: 'Entire house',
    location: 'Kolkata, India',
    coords: { lat: 22.52, lng: 88.35 },
    price: 15000,
    rating: 4.95,
    reviews: 100,
    guests: 8,
    bedrooms: 4,
    beds: 4,
    baths: 3,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Garden'],
    host: { name: 'Chowdhury family', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/201/800/600', 'https://picsum.photos/seed/202/800/600'],
    details: 'Stay in a grand old ancestral home in the quiet, leafy lanes of Ballygunge. Full of antique furniture and character.',
    summary: 'A grand ancestral home in Ballygunge, featuring antique furniture and character in a quiet, leafy setting.'
  },
  {
    id: '62',
    title: 'Artist\'s Den in Jadavpur',
    type: 'Private room',
    location: 'Kolkata, India',
    coords: { lat: 22.49, lng: 88.36 },
    price: 2000,
    rating: 4.8,
    reviews: 300,
    guests: 1,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi'],
    host: { name: 'Sanjay', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/203/800/600', 'https://picsum.photos/seed/204/800/600'],
    details: 'A quirky room in an artist\'s apartment in Jadavpur. Close to the university and the cultural hub of South Kolkata.',
    summary: 'A quirky room in a Jadavpur artist\'s apartment, near the university and South Kolkata\'s cultural hub.'
  },
  // Add 7 more for Hyderabad
  {
    id: '63',
    title: 'Banjara Hills Luxury Villa',
    type: 'Entire villa',
    location: 'Hyderabad, India',
    coords: { lat: 17.41, lng: 78.43 },
    price: 25000,
    rating: 4.98,
    reviews: 70,
    guests: 10,
    bedrooms: 4,
    beds: 5,
    baths: 4,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Pool', 'Home theater'],
    host: { name: 'Reddy', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/205/800/600', 'https://picsum.photos/seed/206/800/600'],
    details: 'An opulent villa in the uber-rich Banjara Hills. Comes with a private pool and a home theater system.',
    summary: 'An opulent Banjara Hills villa with a private pool and home theater.'
  },
  {
    id: '64',
    title: 'HITEC City Serviced Apartment',
    type: 'Entire apartment',
    location: 'Hyderabad, India',
    coords: { lat: 17.44, lng: 78.37 },
    price: 6000,
    rating: 4.7,
    reviews: 200,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Gym', 'Pool'],
    host: { name: 'Cyber Stays', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/207/800/600', 'https://picsum.photos/seed/208/800/600'],
    details: 'A comfortable serviced apartment in HITEC City, the IT hub of Hyderabad. Perfect for long stays for work.',
    summary: 'A comfortable serviced apartment in HITEC City, ideal for extended work stays in Hyderabad\'s IT hub.'
  },
  {
    id: '65',
    title: 'Jubilee Hills Celebrity Home',
    type: 'Entire house',
    location: 'Hyderabad, India',
    coords: { lat: 17.43, lng: 78.40 },
    price: 30000,
    rating: 5.0,
    reviews: 50,
    guests: 8,
    bedrooms: 4,
    beds: 4,
    baths: 4,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Pool', 'Garden'],
    host: { name: 'A-List Host', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/209/800/600', 'https://picsum.photos/seed/210/800/600'],
    details: 'Stay in a house straight out of a movie in Jubilee Hills, home to Tollywood stars. Ultimate luxury and privacy.',
    summary: 'Experience ultimate luxury and privacy in a movie-like house in Jubilee Hills, a Tollywood star neighborhood.'
  },
  {
    id: '66',
    title: 'Begumpet Heritage Room',
    type: 'Private room in house',
    location: 'Hyderabad, India',
    coords: { lat: 17.44, lng: 78.46 },
    price: 4000,
    rating: 4.85,
    reviews: 150,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Air conditioning', 'Breakfast included'],
    host: { name: 'Begum Sahiba', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/211/800/600', 'https://picsum.photos/seed/212/800/600'],
    details: 'A charming room in a beautiful old house in Begumpet. Experience the old-world charm of Hyderabad.',
    summary: 'A charming room in a historic Begumpet house, offering a taste of old-world Hyderabad.'
  },
  {
    id: '67',
    title: 'Gachibowli Studio for Techies',
    type: 'Entire studio',
    location: 'Hyderabad, India',
    coords: { lat: 17.44, lng: 78.34 },
    price: 3500,
    rating: 4.75,
    reviews: 250,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Kitchenette', 'Air conditioning', 'TV'],
    host: { name: 'Tech Pads', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/213/800/600', 'https://picsum.photos/seed/214/800/600'],
    details: 'A compact and modern studio in Gachibowli, close to Microsoft, Amazon, and other major tech campuses.',
    summary: 'A compact, modern studio in Gachibowli, near major tech campuses like Microsoft and Amazon.'
  },
  {
    id: '68',
    title: 'Old City Foodie Paradise',
    type: 'Private room',
    location: 'Hyderabad, India',
    coords: { lat: 17.36, lng: 78.47 },
    price: 2500,
    rating: 4.9,
    reviews: 350,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Air conditioning', 'Food tours'],
    host: { name: 'Aslam', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/215/800/600', 'https://picsum.photos/seed/216/800/600'],
    details: 'A room in the heart of the Old City, perfect for foodies. The host offers curated food tours to the best local joints.',
    summary: 'An Old City room perfect for foodies, with curated food tours to the best local spots.'
  },
  {
    id: '69',
    title: 'Secunderabad Club Proximity',
    type: 'Entire apartment',
    location: 'Hyderabad, India',
    coords: { lat: 17.45, lng: 78.50 },
    price: 7000,
    rating: 4.8,
    reviews: 110,
    guests: 5,
    bedrooms: 2,
    beds: 3,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning'],
    host: { name: 'Col. Rao', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/217/800/600', 'https://picsum.photos/seed/218/800/600'],
    details: 'A comfortable apartment in Secunderabad, close to the famous Secunderabad Club. Quiet and peaceful neighborhood.',
    summary: 'A comfortable apartment in a quiet Secunderabad neighborhood, near the famous Secunderabad Club.'
  },
  // Add 7 more for Pune
  {
    id: '70',
    title: 'Osho Ashram Adjacent Studio',
    type: 'Entire studio',
    location: 'Pune, India',
    coords: { lat: 18.53, lng: 73.88 },
    price: 4000,
    rating: 4.8,
    reviews: 280,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Kitchenette', 'Air conditioning', 'Peaceful'],
    host: { name: 'Swami Prem', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/219/800/600', 'https://picsum.photos/seed/220/800/600'],
    details: 'A serene studio apartment right next to the Osho International Meditation Resort in Koregaon Park. Perfect for spiritual seekers.',
    summary: 'A serene studio next to the Osho Meditation Resort in Koregaon Park, ideal for spiritual seekers.'
  },
  {
    id: '71',
    title: 'Student Hub in Viman Nagar',
    type: 'Private room',
    location: 'Pune, India',
    coords: { lat: 18.56, lng: 73.91 },
    price: 2000,
    rating: 4.6,
    reviews: 400,
    guests: 1,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Shared kitchen', 'Study desk'],
    host: { name: 'Student Homes', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/221/800/600', 'https://picsum.photos/seed/222/800/600'],
    details: 'A budget-friendly private room in a student-centric apartment in Viman Nagar. Close to Symbiosis and other colleges.',
    summary: 'An affordable private room in Viman Nagar, ideal for students, close to Symbiosis and other colleges.'
  },
  {
    id: '72',
    title: 'Hinjewadi IT Park Apartment',
    type: 'Entire apartment',
    location: 'Pune, India',
    coords: { lat: 18.59, lng: 73.73 },
    price: 5000,
    rating: 4.7,
    reviews: 220,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Gym'],
    host: { name: 'IT Stays', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/223/800/600', 'https://picsum.photos/seed/224/800/600'],
    details: 'A modern 2BHK apartment in a large complex in Hinjewadi, the IT hub of Pune. Ideal for corporate stays.',
    summary: 'A modern 2BHK apartment in Hinjewadi, perfect for corporate stays in Pune\'s IT hub.'
  },
  {
    id: '73',
    title: 'Old Pune Wadas Homestay',
    type: 'Private room in house',
    location: 'Pune, India',
    coords: { lat: 18.52, lng: 73.85 },
    price: 3000,
    rating: 4.9,
    reviews: 300,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Authentic experience'],
    host: { name: 'Joshi Kaka', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/225/800/600', 'https://picsum.photos/seed/226/800/600'],
    details: 'Stay in a traditional "Wada" (mansion) in the heart of old Pune. Experience the authentic Puneri culture.',
    summary: 'Experience authentic Puneri culture in a traditional "Wada" mansion in the heart of old Pune.'
  },
  {
    id: '74',
    title: 'Lavasa City View Apartment',
    type: 'Entire apartment',
    location: 'Pune, India',
    coords: { lat: 18.40, lng: 73.50 },
    price: 6000,
    rating: 4.8,
    reviews: 180,
    guests: 4,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    amenities: ['Wifi', 'Kitchenette', 'Air conditioning', 'Lake view'],
    host: { name: 'Weekend Getaways', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/227/800/600', 'https://picsum.photos/seed/228/800/600'],
    details: 'An apartment in Lavasa, a planned city styled on Portofino, Italy. Offers great views of the lake. A good weekend trip from Pune.',
    summary: 'An apartment in Lavasa, a Portofino-styled city, offers lake views, perfect for a weekend trip from Pune.'
  },
  {
    id: '75',
    title: 'Khadki War Memorial Vicinity',
    type: 'Entire house',
    location: 'Pune, India',
    coords: { lat: 18.56, lng: 73.85 },
    price: 8000,
    rating: 4.85,
    reviews: 150,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Garden'],
    host: { name: 'Patil', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/229/800/600', 'https://picsum.photos/seed/230/800/600'],
    details: 'A comfortable house in the cantonment area of Khadki. Peaceful and green surroundings, close to the war memorial.',
    summary: 'A comfortable house in Khadki\'s cantonment area, offering peaceful, green surroundings near the war memorial.'
  },
  {
    id: '76',
    title: 'FC Road Social Pad',
    type: 'Private room',
    location: 'Pune, India',
    coords: { lat: 18.52, lng: 73.84 },
    price: 2500,
    rating: 4.7,
    reviews: 350,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Air conditioning'],
    host: { name: 'Riya', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/231/800/600', 'https://picsum.photos/seed/232/800/600'],
    details: 'A room in an apartment on FC Road, the most happening street in Pune. Surrounded by cafes, restaurants, and shops.',
    summary: 'A room on FC Road, Pune\'s liveliest street, surrounded by cafes, restaurants, and shops.'
  },
  // Add 7 for Udaipur
  {
    id: '77',
    title: 'Ambrai Ghat View Haveli',
    type: 'Private room in haveli',
    location: 'Udaipur, India',
    coords: { lat: 24.57, lng: 73.68 },
    price: 10000,
    rating: 4.95,
    reviews: 200,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Air conditioning', 'Lake view', 'Rooftop restaurant'],
    host: { name: 'Thakur Sahab', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/233/800/600', 'https://picsum.photos/seed/234/800/600'],
    details: 'A room in a heritage haveli with the best view of the City Palace and Lake Pichola from Ambrai Ghat.',
    summary: 'A heritage haveli room with stunning views of the City Palace and Lake Pichola from Ambrai Ghat.'
  },
  {
    id: '78',
    title: 'Laal Ghat Backpacker Hostel',
    type: 'Shared dorm',
    location: 'Udaipur, India',
    coords: { lat: 24.57, lng: 73.68 },
    price: 700,
    rating: 4.8,
    reviews: 800,
    guests: 1,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Lockers', 'Rooftop cafe', 'Lake view'],
    host: { name: 'Bunkyard', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/235/800/600', 'https://picsum.photos/seed/236/800/600'],
    details: 'A lively backpacker hostel in the heart of the old city at Laal Ghat. Has a rooftop cafe with amazing lake views.',
    summary: 'A lively backpacker hostel in the old city\'s Laal Ghat with a rooftop cafe and stunning lake views.'
  },
  {
    id: '79',
    title: 'Fateh Sagar Lake House',
    type: 'Entire house',
    location: 'Udaipur, India',
    coords: { lat: 24.60, lng: 73.68 },
    price: 15000,
    rating: 4.9,
    reviews: 150,
    guests: 8,
    bedrooms: 3,
    beds: 4,
    baths: 3,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Garden', 'Lake view'],
    host: { name: 'Sisodia family', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/237/800/600', 'https://picsum.photos/seed/238/800/600'],
    details: 'A beautiful house overlooking the serene Fateh Sagar Lake. Away from the touristy crowds but still accessible.',
    summary: 'A beautiful, accessible house with serene views of Fateh Sagar Lake, away from tourist crowds.'
  },
  {
    id: '80',
    title: 'Jagdish Temple Homestay',
    type: 'Private room in house',
    location: 'Udaipur, India',
    coords: { lat: 24.57, lng: 73.68 },
    price: 3000,
    rating: 4.85,
    reviews: 300,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Air conditioning'],
    host: { name: 'Pandit ji', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/239/800/600', 'https://picsum.photos/seed/240/800/600'],
    details: 'A simple room in a house in the lane of the famous Jagdish Temple. Experience the spiritual side of Udaipur.',
    summary: 'A simple room in a house on Jagdish Temple lane, offering a spiritual experience in Udaipur.'
  },
  {
    id: '81',
    title: 'Shilpgram Rural Hut',
    type: 'Entire hut',
    location: 'Udaipur, India',
    coords: { lat: 24.60, lng: 73.66 },
    price: 2000,
    rating: 4.7,
    reviews: 250,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    amenities: ['Authentic experience', 'Peaceful'],
    host: { name: 'Local Artisan', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/241/800/600', 'https://picsum.photos/seed/242/800/600'],
    details: 'A traditional mud hut in the Shilpgram artists\' village. A truly unique and rustic experience.',
    summary: 'A unique, rustic mud hut in Shilpgram artists\' village, offering a traditional experience.'
  },
  {
    id: '82',
    title: 'Island Palace on Lake Pichola',
    type: 'Suite in hotel',
    location: 'Udaipur, India',
    coords: { lat: 24.575, lng: 73.68 },
    price: 50000,
    rating: 5.0,
    reviews: 100,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Pool', 'Air conditioning', 'Restaurant', 'Spa', 'Boat service'],
    host: { name: 'Taj Lake Palace', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/243/800/600', 'https://picsum.photos/seed/244/800/600'],
    details: 'The ultimate luxury experience. Stay at the world-famous Taj Lake Palace, an island in the middle of Lake Pichola.',
    summary: 'Experience ultimate luxury at the world-famous Taj Lake Palace, an island hotel in Lake Pichola.'
  },
  {
    id: '83',
    title: 'Aravalli Hills View Villa',
    type: 'Entire villa',
    location: 'Udaipur, India',
    coords: { lat: 24.62, lng: 73.74 },
    price: 20000,
    rating: 4.9,
    reviews: 120,
    guests: 8,
    bedrooms: 4,
    beds: 4,
    baths: 4,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Pool', 'Mountain view'],
    host: { name: 'Mr. Rathore', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/245/800/600', 'https://picsum.photos/seed/246/800/600'],
    details: 'A modern villa with a private pool, nestled in the Aravalli hills. Enjoy panoramic views and tranquility.',
    summary: 'A modern villa with a private pool in the Aravalli hills, offering panoramic views and tranquility.'
  },
  // Add 7 for Munnar
  {
    id: '84',
    title: 'Cardamom Plantation Cottage',
    type: 'Entire cottage',
    location: 'Munnar, India',
    coords: { lat: 10.05, lng: 77.05 },
    price: 8000,
    rating: 4.9,
    reviews: 150,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    amenities: ['Kitchen', 'Garden', 'Spice tour'],
    host: { name: 'George', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/247/800/600', 'https://picsum.photos/seed/248/800/600'],
    details: 'A rustic cottage in the middle of a cardamom plantation. The air is fragrant with spices. The host offers a free spice tour.',
    summary: 'A rustic cottage in a cardamom plantation with fragrant air, offering free spice tours.'
  },
  {
    id: '85',
    title: 'Top Station Viewpoint Homestay',
    type: 'Private room in house',
    location: 'Munnar, India',
    coords: { lat: 10.12, lng: 77.24 },
    price: 4000,
    rating: 4.8,
    reviews: 200,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Home-cooked food', 'Mountain view'],
    host: { name: 'Mary', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/249/800/600', 'https://picsum.photos/seed/250/800/600'],
    details: 'A simple homestay with stunning views, located near the Top Station viewpoint. Enjoy authentic Kerala home-cooked food.',
    summary: 'A simple homestay near Top Station viewpoint with stunning views and authentic Kerala home-cooked food.'
  },
  {
    id: '86',
    title: 'Luxury Resort & Spa',
    type: 'Room in resort',
    location: 'Munnar, India',
    coords: { lat: 10.08, lng: 77.06 },
    price: 15000,
    rating: 4.95,
    reviews: 250,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    amenities: ['Wifi', 'Pool', 'Air conditioning', 'Restaurant', 'Spa'],
    host: { name: 'Club Mahindra', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/251/800/600', 'https://picsum.photos/seed/252/800/600'],
    details: 'Indulge in luxury at this beautiful resort in Munnar. It offers a spa, multiple restaurants, and a range of activities.',
    summary: 'A luxurious Munnar resort with a spa, multiple restaurants, and various activities.'
  },
  {
    id: '87',
    title: 'Treehouse in the Woods',
    type: 'Entire treehouse',
    location: 'Munnar, India',
    coords: { lat: 10.03, lng: 77.01 },
    price: 12000,
    rating: 4.98,
    reviews: 180,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Nature', 'Adventure'],
    host: { name: 'Forest Escapes', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/253/800/600', 'https://picsum.photos/seed/254/800/600'],
    details: 'A unique experience of staying in a treehouse in the middle of a forest. For the adventurous and nature lovers.',
    summary: 'An adventurous treehouse stay in a forest, perfect for nature lovers.'
  },
  {
    id: '88',
    title: 'Echo Point Camping',
    type: 'Tent',
    location: 'Munnar, India',
    coords: { lat: 10.10, lng: 77.10 },
    price: 3000,
    rating: 4.7,
    reviews: 300,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Bonfire', 'Stargazing'],
    host: { name: 'Munnar Adventures', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/255/800/600', 'https://picsum.photos/seed/256/800/600'],
    details: 'Camp under the stars near Echo Point. A great experience for students and budget travelers. Bonfire and music at night.',
    summary: 'An affordable camping experience near Echo Point with bonfires and music, ideal for students and budget travelers.'
  },
  {
    id: '89',
    title: 'Mattupetty Dam View Cottage',
    type: 'Entire cottage',
    location: 'Munnar, India',
    coords: { lat: 10.10, lng: 77.13 },
    price: 9000,
    rating: 4.85,
    reviews: 160,
    guests: 5,
    bedrooms: 2,
    beds: 3,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Mountain view', 'Dam view'],
    host: { name: 'Kumar', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/257/800/600', 'https://picsum.photos/seed/258/800/600'],
    details: 'A cozy cottage with a direct view of the beautiful Mattupetty Dam. Enjoy the misty mountains and serene waters.',
    summary: 'A cozy cottage with a direct view of Mattupetty Dam, offering serene waters and misty mountains.'
  },
  {
    id: '90',
    title: 'Budget Homestay in Munnar Town',
    type: 'Private room',
    location: 'Munnar, India',
    coords: { lat: 10.08, lng: 77.06 },
    price: 1500,
    rating: 4.6,
    reviews: 500,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi'],
    host: { name: 'Joseph', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/259/800/600', 'https://picsum.photos/seed/260/800/600'],
    details: 'A clean and basic room in the heart of Munnar town. Easy access to the market and restaurants.',
    summary: 'A clean, basic room in central Munnar, with easy access to the market and restaurants.'
  },
  // Add 7 for Pondicherry
  {
    id: '91',
    title: 'Auroville Earth-Mud House',
    type: 'Entire house',
    location: 'Pondicherry, India',
    coords: { lat: 12.00, lng: 79.81 },
    price: 5000,
    rating: 4.9,
    reviews: 300,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    amenities: ['Kitchen', 'Garden', 'Peaceful'],
    host: { name: 'Aurovillian', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/261/800/600', 'https://picsum.photos/seed/262/800/600'],
    details: 'An experimental, eco-friendly earth-mud house in the green belt of Auroville. A unique and sustainable living experience.',
    summary: 'An experimental, eco-friendly earth-mud house in Auroville\'s green belt, offering a unique and sustainable living experience.'
  },
  {
    id: '92',
    title: 'Promenade Beach Sea View Apt',
    type: 'Entire apartment',
    location: 'Pondicherry, India',
    coords: { lat: 11.93, lng: 79.83 },
    price: 10000,
    rating: 4.85,
    reviews: 200,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Sea view', 'Balcony'],
    host: { name: 'Francois', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/263/800/600', 'https://picsum.photos/seed/264/800/600'],
    details: 'An apartment on Goubert Avenue with a direct, uninterrupted view of the sea. Watch the sunrise from your balcony.',
    summary: 'An apartment on Goubert Avenue with a balcony offering a direct, uninterrupted sunrise sea view.'
  },
{
    id: '93',
    title: 'Tamil Quarter Heritage Home',
    type: 'Entire house',
    location: 'Pondicherry, India',
    coords: { lat: 11.93, lng: 79.82 },
    price: 8000,
    rating: 4.88,
    reviews: 180,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Courtyard'],
    host: { name: 'Muthu', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/265/800/600', 'https://picsum.photos/seed/266/800/600'],
    details: 'A restored heritage home in the Tamil Quarter of Pondicherry. Experience the local culture and architecture.',
    summary: 'A restored heritage home in Pondicherry\'s Tamil Quarter, offering an immersive cultural and architectural experience.'
  },
  {
    id: '94',
    title: 'Serenity Beach Surfer\'s Hut',
    type: 'Entire hut',
    location: 'Pondicherry, India',
    coords: { lat: 11.96, lng: 79.84 },
    price: 3000,
    rating: 4.7,
    reviews: 250,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Beachfront', 'Surfing lessons'],
    host: { name: 'Kallialay Surf School', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/267/800/600', 'https://picsum.photos/seed/268/800/600'],
    details: 'A basic but cool beach hut at Serenity Beach, home to Pondicherry\'s surfing scene. The host offers surfing lessons.',
    summary: 'A cool, basic beach hut at Serenity Beach, the heart of Pondicherry\'s surf scene, with surfing lessons available.'
  },
  {
    id: '95',
    title: 'Boutique Hotel in White Town',
    type: 'Private room in hotel',
    location: 'Pondicherry, India',
    coords: { lat: 11.93, lng: 79.83 },
    price: 9000,
    rating: 4.9,
    reviews: 220,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Pool', 'Air conditioning', 'Restaurant', 'Cafe'],
    host: { name: 'Le Dupleix', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/269/800/600', 'https://picsum.photos/seed/270/800/600'],
    details: 'A room in a beautifully restored French colonial villa, now a boutique hotel. High-end dining and a chic bar.',
    summary: 'A room in a restored French colonial villa turned boutique hotel, featuring high-end dining and a chic bar.'
  },
  {
    id: '96',
    title: 'Ashram-adjacent Guesthouse',
    type: 'Private room',
    location: 'Pondicherry, India',
    coords: { lat: 11.93, lng: 79.83 },
    price: 2500,
    rating: 4.6,
    reviews: 400,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Air conditioning', 'Peaceful'],
    host: { name: 'Sri Aurobindo Ashram', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/271/800/600', 'https://picsum.photos/seed/272/800/600'],
    details: 'A clean, simple, and peaceful room in a guesthouse affiliated with the Sri Aurobindo Ashram. Perfect for devotees.',
    summary: 'A clean, peaceful room in an ashram-affiliated guesthouse, ideal for devotees of Sri Aurobindo.'
  },
  {
    id: '97',
    title: 'Paradise Beach Camping',
    type: 'Tent',
    location: 'Pondicherry, India',
    coords: { lat: 11.85, lng: 79.79 },
    price: 2000,
    rating: 4.5,
    reviews: 300,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Beachfront', 'Boating'],
    host: { name: 'Pondy Adventures', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/273/800/600', 'https://picsum.photos/seed/274/800/600'],
    details: 'Camp on the beautiful Paradise Beach, which is an island accessible by boat. A basic but thrilling experience.',
    summary: 'A basic but thrilling camping experience on the beautiful, boat-accessible Paradise Beach island.'
  },
  // Add 7 for Srinagar
  {
    id: '98',
    title: 'Nigeen Lake View Houseboat',
    type: 'Entire houseboat',
    location: 'Srinagar, India',
    coords: { lat: 34.11, lng: 74.82 },
    price: 15000,
    rating: 4.95,
    reviews: 250,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    amenities: ['Wifi', 'Meals included', 'Lake view', 'Veranda'],
    host: { name: 'Butt\'s Clermont Houseboats', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/275/800/600', 'https://picsum.photos/seed/276/800/600'],
    details: 'A luxurious houseboat on the quieter and cleaner Nigeen Lake. Offers more privacy and serenity than Dal Lake.',
    summary: 'A luxurious houseboat on serene Nigeen Lake, offering greater privacy than Dal Lake.'
  },
  {
    id: '99',
    title: 'Shalimar Bagh Vicinity Homestay',
    type: 'Private room in house',
    location: 'Srinagar, India',
    coords: { lat: 34.14, lng: 74.87 },
    price: 4000,
    rating: 4.8,
    reviews: 180,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Home-cooked food', 'Garden'],
    host: { name: 'Khan family', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/277/800/600', 'https://picsum.photos/seed/278/800/600'],
    details: 'Stay with a local family in their beautiful home with a saffron and apple garden, near the famous Shalimar Bagh.',
    summary: 'A homestay with a local family, featuring a saffron and apple garden, near Shalimar Bagh.'
  },
  {
    id: '100',
    title: 'The Lalit Grand Palace',
    type: 'Room in palace hotel',
    location: 'Srinagar, India',
    coords: { lat: 34.09, lng: 74.83 },
    price: 25000,
    rating: 4.98,
    reviews: 300,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Pool', 'Restaurant', 'Spa', 'Palace grounds'],
    host: { name: 'The Lalit', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/279/800/600', 'https://picsum.photos/seed/280/800/600'],
    details: 'Stay in the former palace of the Maharaja of Kashmir. Sprawling grounds, regal interiors, and unmatched service.',
    summary: 'A former Maharaja\'s palace with sprawling grounds, regal interiors, and exceptional service.'
  },
  {
    id: '101',
    title: 'Old City Heritage Home',
    type: 'Entire house',
    location: 'Srinagar, India',
    coords: { lat: 34.08, lng: 74.79 },
    price: 9000,
    rating: 4.85,
    reviews: 150,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 2,
    amenities: ['Wifi', 'Kitchen', 'Authentic Kashmiri architecture'],
    host: { name: 'Bhat family', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/281/800/600', 'https://picsum.photos/seed/282/800/600'],
    details: 'A restored heritage home in the old city (Shehr-e-Khaas) of Srinagar. Experience the intricate wood carvings and architecture.',
    summary: 'A restored heritage home in old Srinagar, featuring intricate wood carvings and authentic architecture.'
  },
  {
    id: '102',
    title: 'Gurez Valley Eco-Lodge',
    type: 'Room in lodge',
    location: 'Srinagar, India',
    coords: { lat: 34.63, lng: 74.67 },
    price: 7000,
    rating: 4.9,
    reviews: 100,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Off-grid', 'Trekking', 'River view'],
    host: { name: 'Kashmir Eco Tours', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/283/800/600', 'https://picsum.photos/seed/284/800/600'],
    details: 'For the truly adventurous. An eco-lodge in the remote but stunningly beautiful Gurez Valley. Requires a permit to visit.',
    summary: 'An adventurous eco-lodge in the remote, beautiful Gurez Valley, requiring a permit for entry.'
  },
  {
    id: '103',
    title: 'Pahalgam River-Side Cottage',
    type: 'Entire cottage',
    location: 'Srinagar, India',
    coords: { lat: 34.01, lng: 75.32 },
    price: 12000,
    rating: 4.92,
    reviews: 200,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 2,
    amenities: ['Kitchen', 'Fireplace', 'River view', 'Garden'],
    host: { name: 'Mr. Malik', avatar: 'https://picsum.photos/100/100', isSuperhost: true },
    images: ['https://picsum.photos/seed/285/800/600', 'https://picsum.photos/seed/286/800/600'],
    details: 'A beautiful cottage on the banks of the Lidder river in Pahalgam, a popular day trip from Srinagar. Perfect for nature lovers.',
    summary: 'A beautiful cottage on the Lidder river in Pahalgam, perfect for nature lovers and a popular day trip from Srinagar.'
  },
  {
    id: '104',
    title: 'Budget guesthouse near TRC',
    type: 'Private room',
    location: 'Srinagar, India',
    coords: { lat: 34.07, lng: 74.82 },
    price: 2000,
    rating: 4.5,
    reviews: 400,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi'],
    host: { name: 'Javid', avatar: 'https://picsum.photos/100/100', isSuperhost: false },
    images: ['https://picsum.photos/seed/287/800/600', 'https://picsum.photos/seed/288/800/600'],
    details: 'A basic guesthouse near the Tourist Reception Center in Srinagar. Convenient location and budget-friendly.',
    summary: 'A basic, budget-friendly guesthouse conveniently located near the Tourist Reception Center in Srinagar.'
  }
];

    
